export const IMAGES = {
     // appLogo: { uri: 'S3_URL' },
     appLogo: require('./pexels-pixabay-60597.jpg'),
     register: require('./register.png'),
     signin_email: require('./signin_email.png'),
     loginLogo: require('./Fabmerce-logo-01.png'),//fabmerce logo
     signin_password: require('./signin_password.png'),
     splashImage: require('./fabmercelogoanimation_3.gif'),
     searchBoxLogoFabmerce: require('./Fabmerce_logo_fab.png'),
     discountcardbackground: require('./discountcardbackground.png'),
     unmissabletrendslargeimage: require('./unmissabletrendslargeimage.png'),
     kidsWearLargeImageBackground: require('./Kids.png'),
     EmptyCartImage: require('./emptycart.png'),
     Onboard: require('./onboard.png'),
     Explore: require('./hand_bag_poster.png'),
     accessories: require('./accessories.png'),
     gadgets: require('./gadgets.png'),
     Skin_care: require('./Skin_care.png'),
     beauty_large: require('./beauty_large.png'),
     combo_set: require('./combo_set.png'),
     earings: require('./earrings.png'),
     cos_1: require('./cos_1.png'),
     cos_2: require('./cos_2.png'),
     soap: require('./soap.png'),
     Face_cream: require('./Face_cream.png'),
     chocolets: require('./chocolets.png'),
     nuts: require('./nuts.png'),
     casual_shoe: require('./casual_shoe.png'),
     formalshoe: require('./formalshoe.png'),
     shoe: require('./shoe.png'),
     hand_bags: require('./hand_bags.png'),
     hand_bag1: require('./hand_bag1.png'),
     hand_bag2: require('./hand_bag2.png'),
     Nec: require('./Nec.png'),
}
